spring:
  application:
    name: spring-chain-application
  mandatory-file-encoding: utf-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
  main:
    banner-mode: off
server:
  port: 9092
  undertow:
    accesslog:
      enabled: true
      dir: logs
      rotate: true
      prefix: spring-chain-undertow-access-log.
      suffix: log
  servlet:
    context-path: /spring-chain-application
logging:
  level:
    root: warn
    org.springframework.web: debug
    com.kevin.spring.chain.sample: debug
